<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
    <url>
        <loc>https://psychics1on1.com/</loc>
        <lastmod>2019-12-23T13:39:56-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://psychics1on1.com/abilities/psychic</loc>
        <lastmod>2019-12-23T13:40:05-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://psychics1on1.com/abilities/medium</loc>
        <lastmod>2019-12-23T13:40:23-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://psychics1on1.com/abilities/astrology</loc>
        <lastmod>2019-12-23T13:40:14-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://psychics1on1.com/abilities/palm-reading</loc>
        <lastmod>2019-12-23T13:40:31-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://psychics1on1.com/abilities/tarot-card-reader</loc>
        <lastmod>2019-12-23T13:40:31-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://psychics1on1.com/abilities/clairvoyant</loc>
        <lastmod>2019-12-23T13:40:31-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://psychics1on1.com/abilities/spiritual-healer</loc>
        <lastmod>2019-12-23T13:40:31-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>

    <url>
        <loc>https://psychics1on1.com/apply</loc>
        <lastmod>2019-12-23T13:40:31-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://psychics1on1.com/privacy-policy</loc>
        <lastmod>2019-12-23T13:40:31-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://psychics1on1.com/dmca-policy</loc>
        <lastmod>2019-12-23T13:40:31-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://psychics1on1.com/payment-terms</loc>
        <lastmod>2019-12-23T13:40:31-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://psychics1on1.com/terms</loc>
        <lastmod>2019-12-23T13:40:31-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://psychics1on1.com/about</loc>
        <lastmod>2019-12-23T13:40:31-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://psychics1on1.com/blog</loc>
        <lastmod>2019-12-23T13:40:31-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://www.psychics1on1.com/blog/category/psychic</loc>
        <lastmod>2020-12-16T13:40:31-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
	<url>
        <loc>https://www.psychics1on1.com/blog/category/astrology</loc>
        <lastmod>2020-12-16T13:40:31-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
	<url>
        <loc>https://www.psychics1on1.com/blog/category/horoscopes</loc>
        <lastmod>2020-12-16T13:40:31-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
	<url>
        <loc>https://www.psychics1on1.com/blog/category/wellbeing</loc>
        <lastmod>2020-12-16T13:40:31-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
	<url>
        <loc>https://www.psychics1on1.com/blog/category/medium</loc>
        <lastmod>2020-12-16T13:40:31-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
	<url>
        <loc>https://www.psychics1on1.com/blog/category/clairvoyant</loc>
        <lastmod>2020-12-16T13:40:31-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
	<url>
        <loc>https://www.psychics1on1.com/blog/category/tarot</loc>
        <lastmod>2020-12-16T13:40:31-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
	<url>
        <loc>https://www.psychics1on1.com/blog/category/palm</loc>
        <lastmod>2020-12-16T13:40:31-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
    <url>
        <loc>https://www.psychics1on1.com/paulaabdul</loc>
        <lastmod>2023-05-17T13:40:31-05:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>

        @foreach($psychics as $psychic)
        @if ($psychic->userProfile)            
        <url>
            <loc>{{ URL::route("specialtie.ptofile", [$psychic->userProfile->profile_link]) }}</loc>
            <lastmod>{{ gmdate(DateTime::W3C, strtotime($psychic->updated_at)) }}</lastmod>
            <changefreq>daily</changefreq>
            <priority>1.0</priority>
        </url>
        @endif
    @endforeach

    @foreach($posts as $post)
    <url>
        <loc>{{config('app.url')}}/blog/{{$post->slug}}</loc>
        <lastmod>{{ gmdate(DateTime::W3C, strtotime($post->updated_at)) }}</lastmod>
        <changefreq>weekly</changefreq>
        <priority>0.8</priority>
    </url>
    @endforeach
</urlset>